#!/bin/sh

#
# Replace a delimited text in the input file with text from another file
#
# Copyright (C) 2010 Alessandro Massignan
#                    Francesco Salvestrini
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#

if test "x${1}" = "x"; then
    echo "$me: Missing begin-delimiter"
    exit 1
fi
DELIMITER_BEGIN="${1}"

if test "x${2}" = "x"; then
    echo "$me: Missing end-delimiter"
    exit 1
fi
DELIMITER_END="${2}"

if test "x${3}" = "x" && test ! -r "${3}"; then
    echo "$me: Missing input file"
    exit 1
fi
INPUT_FILE="${3}"

if test "x${4}" = "x" && test ! -r "${4}"; then
    echo "$me: Missing replacement file"
    exit 1
fi
REPLACEMENT_FILE="${4}"

sed -n \
    -e ':b /^.*'$DELIMITER_BEGIN'.*$/{
          p
          r '$REPLACEMENT_FILE'
          x
          be
        }; p; n; bb;' \
    -e ':e /^.*'$DELIMITER_END'.*$/{
          bb
        }; n; be;' \
    <$INPUT_FILE

