FIND_PATH(SDL2_INCLUDE_DIR SDL.h
  HINTS
  $ENV{SDL2DIR}
  PATH_SUFFIXES include/SDL2 include
  PATHS
  /usr/local/include/SDL2
  /usr/include/SDL2
)
MESSAGE("SDL2_INCLUDE_DIR is ${SDL2_INCLUDE_DIR}")

FIND_LIBRARY(SDL2_LIBRARY 
  NAMES SDL2
  HINTS
  $ENV{SDL2DIR}
  PATH_SUFFIXES lib64 lib
  PATHS
  /usr/local
  /usr
)
MESSAGE("SDL2_LIBRARY is ${SDL2_LIBRARY}")


SET(SDL2_FOUND "NO")
IF(SDL2_LIBRARY AND SDL2_INCLUDE_DIR)
  SET(SDL2_FOUND "YES")
ENDIF(SDL2_LIBRARY AND SDL2_INCLUDE_DIR)

