FIND_PATH(SDL2IMAGE_INCLUDE_DIR SDL_image.h
  HINTS
  $ENV{SDL2IMAGEDIR}
  $ENV{SDL2DIR}
  PATH_SUFFIXES include/SDL2 include
  PATHS
  /usr/local/include/SDL2
  /usr/include/SDL2
)
MESSAGE("SDL2IMAGE_INCLUDE_DIR is ${SDL2IMAGE_INCLUDE_DIR}")

FIND_LIBRARY(SDL2IMAGE_LIBRARY
  NAMES SDL2_image
  HINTS
  $ENV{SDL2IMAGEDIR}
  $ENV{SDL2DIR}
  PATH_SUFFIXES lib64 lib
  PATHS
  /usr/local
  /usr
)
MESSAGE("SDL2IMAGE_LIBRARY is ${SDL2IMAGE_LIBRARY}")

SET(SDL2IMAGE_FOUND "NO")
IF(SDL2IMAGE_LIBRARY AND SDL2IMAGE_INCLUDE_DIR)
  SET(SDL2IMAGE_FOUND "YES")
ENDIF(SDL2IMAGE_LIBRARY AND SDL2IMAGE_INCLUDE_DIR)
