FIND_PATH(SDL2MIXER_INCLUDE_DIR SDL_mixer.h
  HINTS
  $ENV{SDL2MIXERDIR}
  $ENV{SDL2DIR}
  PATH_SUFFIXES include/SDL2 include
  PATHS
  /usr/local/include/SDL2
  /usr/include/SDL2
)
MESSAGE("SDL2MIXER_INCLUDE_DIR is ${SDL2MIXER_INCLUDE_DIR}")

FIND_LIBRARY(SDL2MIXER_LIBRARY
  NAMES SDL2_mixer
  HINTS
  $ENV{SDL2MIXERDIR}
  $ENV{SDL2DIR}
  PATH_SUFFIXES lib64 lib
  PATHS
  /usr/local
  /usr
)
MESSAGE("SDL2MIXER_LIBRARY is ${SDL2MIXER_LIBRARY}")

SET(SDL2MIXER_FOUND "NO")
IF(SDL2MIXER_LIBRARY AND SDL2MIXER_INCLUDE_DIR)
  SET(SDL2MIXER_FOUND "YES")
ENDIF(SDL2MIXER_LIBRARY AND SDL2MIXER_INCLUDE_DIR)
